data1 = read.csv(file = 'Downloads/data3.csv')
m = mean(data1$Data)
s = sd(data1$Data)
se = s/sqrt(length(data1$Data))
print("mean for the first graph = ", quote = FALSE)
print(m)
print("standard error for the first graph = ", quote = FALSE)
print(se)
plot(ecdf(data1$Data), xlab = "Measurement Number", ylab = "Measurement", main = "CDF")

#getting the data for the second half
dataframe1 = read.csv(file = 'Downloads/100.2.csv')
dataframe2 = read.csv(file = 'Downloads/200.2.csv')
dataframe3 = read.csv(file = 'Downloads/300.2.csv')
dataframe4 = read.csv(file = 'Downloads/400.2.csv')
dataframe5 = read.csv(file = 'Downloads/500.2.csv')
dataframe6 = read.csv(file = 'Downloads/600.2.csv')
dataframe7 = read.csv(file = 'Downloads/700.2.csv')
dataframe8 = read.csv(file = 'Downloads/800.2.csv')
dataframe9 = read.csv(file = 'Downloads/900.2.csv')
dataframe10 = read.csv(file = 'Downloads/1000.2.csv')

#creating the x axis
x = list(100, 200, 300, 400, 500, 600, 700, 800, 900, 1000)

#creating the y axis
s1 = sd(dataframe1$data)
se1 = s1/sqrt(length(dataframe1$data))
s2 = sd(dataframe2$data)
se2 = s2/sqrt(length(dataframe2$data))
s3 = sd(dataframe3$data)
se3 = s3/sqrt(length(dataframe3$data))
s4 = sd(dataframe4$data)
se4 = s4/sqrt(length(dataframe4$data))
s5 = sd(dataframe5$data)
se5 = s5/sqrt(length(dataframe5$data))
s6 = sd(dataframe6$data)
se6 = s6/sqrt(length(dataframe6$data))
s7 = sd(dataframe7$data)
se7 = s7/sqrt(length(dataframe7$data))
s8 = sd(dataframe8$data)
se8 = s8/sqrt(length(dataframe8$data))
s9 = sd(dataframe9$data)
se9 = s9/sqrt(length(dataframe9$data))
s10 = sd(dataframe10$data)
se10 = s10/sqrt(length(dataframe10$data))
y = list(se1, se2, se3, se4, se5, se6, se7, se8, se9, se10)

#Creating the graph
plot(x, y, xlab = "Measurement Number", ylab = "Measurement", main = "Scatterplot of Standard Error")